In [201]:
# with for file read and write
with open('input.txt', 'r', encoding='utf-8') as f:
    # 读取文件中所有内容，并将其存储在变量 text 中。
    text = f.read()

In [202]:
# text is string type, len() return character numbers in str
print("length in characters: ", len(text))

length in characters:  1115394


In [203]:
# This code prints out the first 1000 (0 -> 999) characters of the text string and if the string is less than 1000, it prints out the entire string
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [204]:
# unique sorted characters
chars = sorted(list(set(text)))
vocal_size = len(chars)
print(chars)
print(''.join(chars))
print(vocal_size)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [205]:
# mapping characters to interger
stoi = {ch: i for i, ch in enumerate(chars)}
print(stoi)
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] # str -> number list []
decode = lambda l: ''.join([itos[i] for i in l]) # number list -> str
print(encode("dadb"))
print(decode(encode("dadb")))
# print(''.join(decode(encode("dadb"))))

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
[42, 39, 42, 40]
dadb


In [206]:
import torch
# "dadb" -> [42, 39, 42, 39] -> tensor([42, 39, 42, 39])
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype) # torch.Size([1115394]) torch.int64
print(data[:1000]) 

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [207]:
# split up the data into training and validation sets
# 90% training, 10% validation
n = int(0.9 * len(data))
train_data, val_data = data[:n], data[n:]

In [208]:
block_size = 8
train_data[:block_size+1]
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"input is {context} -> target is {target}")

input is tensor([18]) -> target is 47
input is tensor([18, 47]) -> target is 56
input is tensor([18, 47, 56]) -> target is 57
input is tensor([18, 47, 56, 57]) -> target is 58
input is tensor([18, 47, 56, 57, 58]) -> target is 1
input is tensor([18, 47, 56, 57, 58,  1]) -> target is 15
input is tensor([18, 47, 56, 57, 58,  1, 15]) -> target is 47
input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) -> target is 58


In [209]:
# set the seed for reproducibility
torch.manual_seed(1337)
batch_size = 4 # for parallel
block_size = 8 # context length

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # ix be like tensor([ 76049, 234249, 934904, 560986])
    # print(ix)
    # print(data[76049])
    x = torch.stack([data[i:i+block_size] for i in ix])
    # data[76049:76049+8]
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, : t+1]
        target = yb[b, t]
        print(f'when input is {context.tolist()} the target :{target}')

    

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target :43
when input is [24, 43] the target :58
when input is [24, 43, 58] the target :5
when input is [24, 43, 58, 5] the target :57
when input is [24, 43, 58, 5, 57] the target :1
when input is [24, 43, 58, 5, 57, 1] the target :46
when input is [24, 43, 58, 5, 57, 1, 46] the target :43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target :39
when input is [44] the target :53
when input is [44, 53] the target :56
when input is [44, 53, 56] the target :1
when input is [44, 53, 56, 1] the target :58
when input is [44, 53, 56, 1, 58] the target :46
when input is [44, 53

In [210]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLLM(nn.Module):

    def __init__(self, vocal_size) -> None:
        super().__init__()
        # vocal_size个词汇，每个词汇映射成tensor[vocal_size]的一维向量
        # vocal_size is 65
        # vocal_size = ['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 
        # 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 
        # 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
        self.token_embedding_table = nn.Embedding(vocal_size, vocal_size)

    # xb -> idx, yb -> target
    # xb 中的每一个元素都被映射到一个65大小的一位张量中
    def forward(self, idx, targets=None):

        # (4,8) -> (4,8,65)
        logits = self.token_embedding_table(idx)

        if targets is  None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # (32, 65)
            targets = targets.view(B*T)  # (32)
            loss = F.cross_entropy(logits, targets)
            # 训练train loss就是在调整每个字符的嵌入向量

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # 调用self.forward(idx)
            logits, loss = self(idx)
            # print(f'logits size is {logits.shape}')
            # print(f'loss is {loss}')
            # 取所有批次的最后一个数据的嵌入表示 (B, T, C)
            """
            tensor([[24, 43, 58,  5, 57,  1, 46, 43],
                    [44, 53, 56,  1, 58, 46, 39, 58],
                    [52, 58,  1, 58, 46, 39, 58,  1],
                    [25, 17, 27, 10,  0, 21,  1, 54]])
            选 43, 58, 1, 54 对应的嵌入表示
            """
            logits = logits[:, -1, :] # becomes (B, C)
            # print(f'logits all batch last number embbding size is {logits.shape}')
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # print(f'softmax = {probs}')
            # 返回softmax中权重最大的那个值的索引
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # print(f'idx_next = {idx_next}')
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
            # print(f'idx = {idx}')
        return idx
    
model = BigramLLM(vocal_size)
logits, loss = model(xb, yb)
print(logits.shape, logits)
print(loss)
# idx = tensor([[0]]), 
print(torch.zeros((2, 1), dtype=torch.long))
print(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100).shape)
print(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100))
print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65]) tensor([[-1.5101, -0.0948,  1.0927,  ..., -0.6126, -0.6597,  0.7624],
        [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594],
        [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
        ...,
        [-2.1910, -0.7574,  1.9656,  ..., -0.3580,  0.8585, -0.6161],
        [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
        [-0.6787,  0.8662, -1.6433,  ...,  2.3671, -0.7775, -0.2586]],
       grad_fn=<ViewBackward0>)
tensor(4.8786, grad_fn=<NllLossBackward0>)
tensor([[0],
        [0]])
torch.Size([1, 101])
tensor([[ 0, 54, 42, 41, 40, 44, 12, 54, 19, 36, 43, 54, 63, 42, 38, 22, 31, 56,
         18,  3, 22, 56, 55, 58,  2, 10, 61, 61, 35, 31, 64, 28, 26, 62, 40, 48,
         28, 47, 16,  4, 29,  2, 39, 11, 63, 26, 58,  3, 23, 56,  3, 53,  7, 45,
         15,  3, 35, 31, 48, 22, 55, 44, 14, 23, 14, 63, 31, 23, 58, 31, 23, 54,
         61, 26, 26, 44, 63, 50,  4, 61, 10, 55,  7, 48, 50, 59, 14, 39, 58, 16,
          3, 24, 

In [211]:
# creat pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
# (32, 8)
batch_size = 32

for steps in range(100):

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.6848883628845215


In [212]:
print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


Jbf$Vb q-gCOcPcUhOnxJGUGSPJWT:.?ujmJFoiNL&A'DxY,prZ?qdT;hoo'dHooXXlxf'WkHK&u3Q?rqUi.kz;?Yx?C&u3Qbfzxlyh'Vl:zyxjKXgC?
lv'QKFiBeviNxO'm!Upm$srm&TqViqiBD3HBP!juEOpmZJyF$Fwfy!PlvWPFC
&WDdP!Ko,px
x
tREOE;AJ.BeXkylOVD3KHp$e?nD,.SFbWWI'ubcL!q-tU;aXmJ&uGXHxJXI&Z!gHRpajj;l.
pTErIBjx;JKIgoCnLGXrJSP!AU-AcbczR?aytqQmBxZb:txqfSBj$I&
gXxy,j,SYgOmgXAaVzLXxlVSP!uSq 3!UM&vcL&yN!zXiA.da-mZ3Izkm!a;Ilkzdd -gwCjN.ivvhM;TBCPOm'p$JO qVJwfRCV,qdPW3vim3QQCj$yNTlPltp$GJhFV.gq-mu?dFnp EcixjHgaZ';JUzYesEvHdZSV;;Akd fmOs$YI


In [213]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation" 加权聚合
torch.manual_seed(42)
# 归一化的3x3的下三角矩阵
a = torch.tril(torch.ones(3, 3))
print(a)
# torch.sum...沿着行求和，并保持原本的维度
a = a / torch.sum(a, 1, keepdim=True)
print(a)
b = torch.randint(0, 10, (3,2)).float()
print(b)
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)




tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [214]:
# toy example
torch.manual_seed(1337)
B, T, C = 4, 8, 2
x = torch.randn(B, T, C)
print(x.shape, x)

torch.Size([4, 8, 2]) tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])


In [215]:
# Version 1 for loop
"""
    We want x[b,t] = mean_{i<=t} x[b,i]
    用显式的for循环计算
"""
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        # 0 <= x < t+1
        xprev = x[b, : t+1, :]
        print(f'xprev = {xprev}')
        # 对列求和并求平均，-> 生成(C, )的一维向量(keepdim = True)
        print(f'torch.mean(xprev, 0) = {torch.mean(xprev, 0)}')
        xbow[b, t, ] = torch.mean(xprev, 0)

print(xbow)

xprev = tensor([[ 0.1808, -0.0700]])
torch.mean(xprev, 0) = tensor([ 0.1808, -0.0700])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152]])
torch.mean(xprev, 0) = tensor([-0.0894, -0.4926])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255]])
torch.mean(xprev, 0) = tensor([ 0.1490, -0.3199])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643]])
torch.mean(xprev, 0) = tensor([ 0.3504, -0.2238])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679]])
torch.mean(xprev, 0) = tensor([0.3525, 0.0545])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102]])
torch.mean(xprev, 0) = tensor([ 0.0688, -0.0396])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.915

In [216]:
# Version 2 matrix multiply
"""
    使用循环计算的xbow和使用矩阵运算技巧(权重矩阵和矩阵乘法)计算的xbow2在数值上是相等的。
    这种方法利用了线性代数中的矩阵乘法来提高效率并简化代码,尤其是当处理大型数据集时,避免了显式的Python循环。
"""
wei = torch.tril(torch.ones(T, T)) # (8, 8)
print(f'wei = {wei}')
wei = wei / wei.sum(1, keepdim=True) # (8, 8)
print(f'wei after divide sum {wei}')
print(x.shape)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
print(xbow2.shape)
print(f'xbow = {xbow}')
print(f'xbow2 = {xbow2}')
# 检查两个张量xbow和xbow2是否在数值上足够接近，即它们是否几乎相等(用默认阈值)
print(torch.allclose(xbow, xbow2, atol=1e-6))

wei = tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei after divide sum tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
torch.Size([4, 8, 2])
torch.Size([4, 8, 2])

In [217]:
# version 3 use Softmax
tril = torch.tril(torch.ones(T,T))
# print(f'tril = {tril}')
wei = torch.zeros((T,T))
# print(f'wei = {wei}')
wei = wei.masked_fill(tril == 0, float('-inf'))
# print(f'after mask = {wei}')
wei = F.softmax(wei, dim=1) # 最后一个维度 1 or -1
# print(f'after softmax = {wei}')
xbow3 = wei @ x
# print(x.shape)
print(torch.allclose(xbow, xbow3, atol=1e-6))
print(f'xbow = {xbow}')
print(f'xbow3 = {xbow3}')
print(xbow==xbow3)

True
xbow = tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])
xbow3 = tensor([[[ 0.1808, -0.0700],
         [-0.08

In [218]:
# version 4: self-attenion!!!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
# 设置单个注意力头的尺寸为16
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x) # (B, T, C)
q = query(x) # (B, T, C)
# wei = q @ k.transpose(-2, -1) / head_size**0.5 # (B, T, T)
"""
    q -> (T, 16) T = "I", "am", "a", "student"
    k -> (16, T)
    当我们完成所有的行列组合后，我们得到了一个(T, T)的矩阵，
    其中每个元素代表不同时间步之间的相互关系。将这个过程重复B次（对于每个批次），
    我们就得到了一个形状为(B, T, T)的三维张量，其中每个(T, T)矩阵都包含了一个样本内部各个时间步之间的关系。
"""
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) -> (B, T, T)
# print(f'wei = {wei}')
tril = torch.tril(torch.ones(T,T))
# print(f'tril = {tril}')
# 上三角元素改成负无穷
print(f'wei[0]_before_mask = {wei[0]}')
wei = wei.masked_fill(tril == 0, float('-inf'))
print(f'wei[0]_after_mask = {wei[0]}')
# print(f'wei_after_mask = {wei}')
wei = F.softmax(wei, dim=-1) 
# print(f'wei_after_softmax = {wei}')

v = value(x) # (B, T, 16)
print(v.shape)

out = wei @ v # (B, T, T) @ (B, T, 16) -> (B, T, 16)
print(out.shape)
print(wei[0])

wei[0]_before_mask = tensor([[-1.7629, -1.3011,  0.5652,  2.1616, -1.0674,  1.9632,  1.0765, -0.4530],
        [-3.3334, -1.6556,  0.1040,  3.3782, -2.1825,  1.0415, -0.0557,  0.2927],
        [-1.0226, -1.2606,  0.0762, -0.3813, -0.9843, -1.4303,  0.0749, -0.9547],
        [ 0.7836, -0.8014, -0.3368, -0.8496, -0.5602, -1.1701, -1.2927, -1.0260],
        [-1.2566,  0.0187, -0.7880, -1.3204,  2.0363,  0.8638,  0.3719,  0.9258],
        [-0.3126,  2.4152, -0.1106, -0.9931,  3.3449, -2.5229,  1.4187,  1.2196],
        [ 1.0876,  1.9652, -0.2621, -0.3158,  0.6091,  1.2616, -0.5484,  0.8048],
        [-1.8044, -0.4126, -0.8306,  0.5898, -0.7987, -0.5856,  0.6433,  0.6303]],
       grad_fn=<SelectBackward0>)
wei[0]_after_mask = tensor([[-1.7629,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-3.3334, -1.6556,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-1.0226, -1.2606,  0.0762,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.7836, -0.8

In [219]:
k = torch.randn(B, T, head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

# 计算张量的方差
print(k.var())
print(q.var())
print(wei.var())

# 缩放对于softmax的影响
print(torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1))
print(torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1))

tensor(1.0449)
tensor(1.0700)
tensor(1.0918)
tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


In [220]:
"""
    数据：
    [[1, 2, 3],
     [2, 3, 4],
     [3, 4, 5],
     [4, 5, 6]]
    层归一化：对每个样本的所有特征行进行归一化,均值=2, 标准差=0.8165
    [[(1 - 2) / 0.8165, (2 - 2) / 0.8165, (3 - 2) / 0.8165],
     [(2 - 3) / 0.8165, (3 - 3) / 0.8165, (4 - 3) / 0.8165],
     [(3 - 4) / 0.8165, (4 - 4) / 0.8165, (5 - 4) / 0.8165],
     [(4 - 5) / 0.8165, (5 - 5) / 0.8165, (6 - 5) / 0.8165]]
    批归一化：对所有样本的每个特征（列）计算均值和标准差,均值=2.5, 标准差=1.29099
    [[(1 - 2.5) / 1.29099, (2 - 3.5) / 1.29099, (3 - 4.5) / 1.29099],
     [(2 - 2.5) / 1.29099, (3 - 3.5) / 1.29099, (4 - 4.5) / 1.29099],
     [(3 - 2.5) / 1.29099, (4 - 3.5) / 1.29099, (5 - 4.5) / 1.29099],
     [(4 - 2.5) / 1.29099, (5 - 3.5) / 1.29099, (6 - 4.5) / 1.29099]]

"""
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(4)
x = torch.randn(5, 4) # batch size 32 of 100-dimensional vectors
print(x)
x = module(x)
print(f'after LayerNorm1d -> {x}')
print(x.shape)
# batch normalization
print(x[:, 0].mean(), x[:, 0].std())
# layer normalization
print(x[0,:].mean(), x[0,:].std()) 

tensor([[ 0.1808, -0.0700, -0.3596, -0.9152],
        [-2.0371,  0.4931,  1.4870,  0.5910],
        [-0.0476, -1.0996, -1.7524, -1.0971],
        [ 0.4478, -0.8016,  1.5236,  2.5086],
        [ 0.1662,  1.2055,  0.1883, -2.1600]])
after LayerNorm1d -> tensor([[ 1.0015,  0.4692, -0.1456, -1.3250],
        [-1.4331,  0.2374,  0.8936,  0.3021],
        [ 1.3491, -0.1424, -1.0679, -0.1388],
        [-0.3316, -1.2096,  0.4245,  1.1166],
        [ 0.2219,  0.9512,  0.2374, -1.4105]])
torch.Size([5, 4])
tensor(0.1616) tensor(1.1074)
tensor(2.9802e-08) tensor(1.0000)
