In [115]:
# with for file read and write
with open('input.txt', 'r', encoding='utf-8') as f:
    # 读取文件中所有内容，并将其存储在变量 text 中。
    text = f.read()

In [116]:
# text is string type, len() return character numbers in str
print("length in characters: ", len(text))

length in characters:  1115394


In [117]:
# This code prints out the first 1000 (0 -> 999) characters of the text string and if the string is less than 1000, it prints out the entire string
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [118]:
# unique sorted characters
chars = sorted(list(set(text)))
vocal_size = len(chars)
print(chars)
print(''.join(chars))
print(vocal_size)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [119]:
# mapping characters to interger
stoi = {ch: i for i, ch in enumerate(chars)}
print(stoi)
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] # str -> number list []
decode = lambda l: ''.join([itos[i] for i in l]) # number list -> str
print(encode("dadb"))
print(decode(encode("dadb")))
# print(''.join(decode(encode("dadb"))))

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
[42, 39, 42, 40]
dadb


In [120]:
import torch
# "dadb" -> [42, 39, 42, 39] -> tensor([42, 39, 42, 39])
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype) # torch.Size([1115394]) torch.int64
print(data[:1000]) 

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [121]:
# split up the data into training and validation sets
# 90% training, 10% validation
n = int(0.9 * len(data))
train_data, val_data = data[:n], data[n:]

In [122]:
block_size = 8
train_data[:block_size+1]
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"input is {context} -> target is {target}")

input is tensor([18]) -> target is 47
input is tensor([18, 47]) -> target is 56
input is tensor([18, 47, 56]) -> target is 57
input is tensor([18, 47, 56, 57]) -> target is 58
input is tensor([18, 47, 56, 57, 58]) -> target is 1
input is tensor([18, 47, 56, 57, 58,  1]) -> target is 15
input is tensor([18, 47, 56, 57, 58,  1, 15]) -> target is 47
input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) -> target is 58


In [123]:
# set the seed for reproducibility
torch.manual_seed(1337)
batch_size = 4 # for parallel
block_size = 8 # context length

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # ix be like tensor([ 76049, 234249, 934904, 560986])
    # print(ix)
    # print(data[76049])
    x = torch.stack([data[i:i+block_size] for i in ix])
    # data[76049:76049+8]
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, : t+1]
        target = yb[b, t]
        print(f'when input is {context.tolist()} the target :{target}')

    

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target :43
when input is [24, 43] the target :58
when input is [24, 43, 58] the target :5
when input is [24, 43, 58, 5] the target :57
when input is [24, 43, 58, 5, 57] the target :1
when input is [24, 43, 58, 5, 57, 1] the target :46
when input is [24, 43, 58, 5, 57, 1, 46] the target :43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target :39
when input is [44] the target :53
when input is [44, 53] the target :56
when input is [44, 53, 56] the target :1
when input is [44, 53, 56, 1] the target :58
when input is [44, 53, 56, 1, 58] the target :46
when input is [44, 53

In [124]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLLM(nn.Module):

    def __init__(self, vocal_size) -> None:
        super().__init__()
        # vocal_size个词汇，每个词汇映射成tensor[vocal_size]的一维向量
        # vocal_size is 65
        # vocal_size = ['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 
        # 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 
        # 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
        self.token_embedding_table = nn.Embedding(vocal_size, vocal_size)

    # xb -> idx, yb -> target
    # xb 中的每一个元素都被映射到一个65大小的一位张量中
    def forward(self, idx, targets=None):

        # (4,8) -> (4,8,65)
        logits = self.token_embedding_table(idx)

        if targets is  None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # (32, 65)
            targets = targets.view(B*T)  # (32)
            loss = F.cross_entropy(logits, targets)
            # 训练train loss就是在调整每个字符的嵌入向量

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # 调用self.forward(idx)
            logits, loss = self(idx)
            # print(f'logits size is {logits.shape}')
            # print(f'loss is {loss}')
            # 取所有批次的最后一个数据的嵌入表示 (B, T, C)
            """
            tensor([[24, 43, 58,  5, 57,  1, 46, 43],
                    [44, 53, 56,  1, 58, 46, 39, 58],
                    [52, 58,  1, 58, 46, 39, 58,  1],
                    [25, 17, 27, 10,  0, 21,  1, 54]])
            选 43, 58, 1, 54 对应的嵌入表示
            """
            logits = logits[:, -1, :] # becomes (B, C)
            # print(f'logits all batch last number embbding size is {logits.shape}')
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # print(f'softmax = {probs}')
            # 返回softmax中权重最大的那个值的索引
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # print(f'idx_next = {idx_next}')
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
            # print(f'idx = {idx}')
        return idx
    
model = BigramLLM(vocal_size)
logits, loss = model(xb, yb)
print(logits.shape, logits)
print(loss)
# idx = tensor([[0]]), 
print(torch.zeros((2, 1), dtype=torch.long))
print(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100).shape)
print(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100))
print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65]) tensor([[-1.5101, -0.0948,  1.0927,  ..., -0.6126, -0.6597,  0.7624],
        [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594],
        [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
        ...,
        [-2.1910, -0.7574,  1.9656,  ..., -0.3580,  0.8585, -0.6161],
        [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
        [-0.6787,  0.8662, -1.6433,  ...,  2.3671, -0.7775, -0.2586]],
       grad_fn=<ViewBackward0>)
tensor(4.8786, grad_fn=<NllLossBackward0>)
tensor([[0],
        [0]])
torch.Size([1, 101])
tensor([[ 0, 54, 42, 41, 40, 44, 12, 54, 19, 36, 43, 54, 63, 42, 38, 22, 31, 56,
         18,  3, 22, 56, 55, 58,  2, 10, 61, 61, 35, 31, 64, 28, 26, 62, 40, 48,
         28, 47, 16,  4, 29,  2, 39, 11, 63, 26, 58,  3, 23, 56,  3, 53,  7, 45,
         15,  3, 35, 31, 48, 22, 55, 44, 14, 23, 14, 63, 31, 23, 58, 31, 23, 54,
         61, 26, 26, 44, 63, 50,  4, 61, 10, 55,  7, 48, 50, 59, 14, 39, 58, 16,
          3, 24, 

In [125]:
# creat pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
# (32, 8)
batch_size = 32

for steps in range(100):

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.6848883628845215


In [126]:
print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


Jbf$Vb q-gCOcPcUhOnxJGUGSPJWT:.?ujmJFoiNL&A'DxY,prZ?qdT;hoo'dHooXXlxf'WkHK&u3Q?rqUi.kz;?Yx?C&u3Qbfzxlyh'Vl:zyxjKXgC?
lv'QKFiBeviNxO'm!Upm$srm&TqViqiBD3HBP!juEOpmZJyF$Fwfy!PlvWPFC
&WDdP!Ko,px
x
tREOE;AJ.BeXkylOVD3KHp$e?nD,.SFbWWI'ubcL!q-tU;aXmJ&uGXHxJXI&Z!gHRpajj;l.
pTErIBjx;JKIgoCnLGXrJSP!AU-AcbczR?aytqQmBxZb:txqfSBj$I&
gXxy,j,SYgOmgXAaVzLXxlVSP!uSq 3!UM&vcL&yN!zXiA.da-mZ3Izkm!a;Ilkzdd -gwCjN.ivvhM;TBCPOm'p$JO qVJwfRCV,qdPW3vim3QQCj$yNTlPltp$GJhFV.gq-mu?dFnp EcixjHgaZ';JUzYesEvHdZSV;;Akd fmOs$YI


In [127]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation" 加权聚合
torch.manual_seed(42)
# 归一化的3x3的下三角矩阵
a = torch.tril(torch.ones(3, 3))
print(a)
# torch.sum...沿着行求和，并保持原本的维度
a = a / torch.sum(a, 1, keepdim=True)
print(a)
b = torch.randint(0, 10, (3,2)).float()
print(b)
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)




tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [128]:
# toy example
torch.manual_seed(1337)
B, T, C = 4, 8, 2
x = torch.randn(B, T, C)
print(x.shape, x)

torch.Size([4, 8, 2]) tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])


In [132]:
# Version 1 for loop
"""
    We want x[b,t] = mean_{i<=t} x[b,i]
    用显式的for循环计算
"""
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        # 0 <= x < t+1
        xprev = x[b, : t+1, :]
        print(f'xprev = {xprev}')
        # 对列求和并求平均，-> 生成(C, )的一维向量(keepdim = True)
        print(f'torch.mean(xprev, 0) = {torch.mean(xprev, 0)}')
        xbow[b, t, ] = torch.mean(xprev, 0)

print(xbow)

xprev = tensor([[ 0.1808, -0.0700]])
torch.mean(xprev, 0) = tensor([ 0.1808, -0.0700])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152]])
torch.mean(xprev, 0) = tensor([-0.0894, -0.4926])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255]])
torch.mean(xprev, 0) = tensor([ 0.1490, -0.3199])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643]])
torch.mean(xprev, 0) = tensor([ 0.3504, -0.2238])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679]])
torch.mean(xprev, 0) = tensor([0.3525, 0.0545])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102]])
torch.mean(xprev, 0) = tensor([ 0.0688, -0.0396])
xprev = tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.915

In [135]:
# Version 2 matrix multiply
"""
    使用循环计算的xbow和使用矩阵运算技巧(权重矩阵和矩阵乘法)计算的xbow2在数值上是相等的。
    这种方法利用了线性代数中的矩阵乘法来提高效率并简化代码,尤其是当处理大型数据集时,避免了显式的Python循环。
"""
wei = torch.tril(torch.ones(T, T))
print(f'wei = {wei}')
wei = wei / wei.sum(1, keepdim=True)
print(f'wei after divide sum {wei}')
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
print(f'xbow2 = {xbow2}')
# 检查两个张量xbow和xbow2是否在数值上足够接近，即它们是否几乎相等(用默认阈值)
torch.allclose(xbow, xbow2)

wei = tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei after divide sum tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
xbow2 = tensor([[[ 0.1808, -0.0700],
      

True

In [143]:
# version 3 use Softmax
tril = torch.tril(torch.ones(T,T))
print(f'tril = {tril}')
wei = torch.zeros((T,T))
print(f'tril = {wei}')
wei = wei.masked_fill(tril == 0, float('-inf'))
print(f'after mask = {wei}')
wei = F.softmax(wei, dim=1) # 最后一个维度 1 or -1
print(f'after softmax = {wei}')
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

tril = tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tril = tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
after mask = tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, 

True

In [ ]:
# version 4: self-attenion!!!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16